### ISSUE TITLE
Make the dark variant cloneable

### ISSUE THREAD

**Issue by UndarkAido** [Jazqa/adwaita-tweaks#3]
Just for ease of use, I thought this would be nice. Would it need to be a separate branch?

**Comment by Jazqa** [comment]
I'll do this as soon as I get on my computer, which should be tomorrow (8-12 hours). I'll probably make a separate branch so they can both be installed via cloning (instead of having to move two cloned folders into the ~/.themes folder). 

The dark theme is basically cloneable already as the main theme comes bundled with the dark theme ("-dark"-files), the GNOME tweak tool just doesn't recognize it as a theme of it's own, but allows the use of darker windows.

**Comment by UndarkAido** [comment]
Awesome!

**Comment by Jazqa** [comment]
Sorry this took a while. A new repository would make cloning much easier while a new branch makes things way more difficult.

I tried making a new branch but both branches would clone under the same name and branching included a plenty of other difficulties. A new repository makes more sense.

**Comment by UndarkAido** [comment]
How is branching more complicated than creating a whole extra repo?

**Comment by Jazqa** [comment]
I'm relatively new to git. The branches worked perfect locally but cloning was more complicated than I would have liked. I'll tinker with it a bit, sort it out and re-create the dark branch.

**Comment by Jazqa** [comment]
It's up again. I didn't mean it was more complicated for me as a maintainer but for the person cloning the repository.

If you want to install it via cloning you'll have to specify the branch and the target folder (if you've also cloned the master branch). Guess it's easy enough and I can include it in the readme-file.

`git clone -b dark https://github.com/Jazqa/adwaita-tweaks.git adwaita-tweaks-dark`

Good enough for closing?

**Comment by UndarkAido** [comment]
Yeah, thank you!
